version: 3
services:
  audition:
    container_name: audition
    image: elkarto91/audirepo:auditionimage
    hostname: audition
    build:
      context: .
      dockerfile: Dockerfile
    environment:
    networks:
      auditionnet
    volumes:
    -./go/src/audition
    ports:
    - 8080
    depends_on:
      - db
    links:
      - db
    labels:


